#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Christian Meter"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "BookNook LED"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.1.0"
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 2
